Replace ProsperStack with BareMetrics Cancellations
Kong/insomnia.rest pull request #83
Opened 2020-11-26 17:50 UTC by DMarby

![image](https://user-images.githubusercontent.com/174626/100380943-2a2ef180-3018-11eb-9f5c-63899aab6033.png)

2020-11-26 17:51 UTC, DMarby commented on src/lib/common/cancel.js
> +      <button id="barecancel-trigger" className="button mt-3">Cancel Subscription</button>
Baremetrics does not correctly handle links with click handlers, hence why this was changed to be just the button, visually it looks the same as before.

2020-11-26 17:53 UTC, DMarby commented on src/lib/common/cancel.js
> +          customer_oid: billingDetails.customerId,
The page is reloaded upon sign out, so this never needs to change.

2020-11-27 01:06 UTC, develohpanda requested changes
Looks good, one question about how we're appending the script

2020-11-27 01:06 UTC, develohpanda commented on src/lib/common/cancel.js
> +          callback_send: cancellationCallback,
I'm assuming `this._handleCancel` is being wrapped because it's being set on the `window` object, and this can't be `callback_send: this._handleCancel`?

2020-11-27 01:06 UTC, develohpanda commented on src/lib/common/cancel.js
> +      document.body.appendChild(s);
I know it's an unlikely case but I'm thinking there can be really adverse behavior if this component is re-mounted? Is there a need to `id` the script and ensure we only ever have one on the page?

Alternatively, we could include this script addition in the `if (!window.barecancel)` conditional.

2020-11-27 06:40 UTC, DMarby commented on src/lib/common/cancel.js
> +  _handleCancel = async e => {
Good catch!

2020-11-27 06:40 UTC, DMarby commented on src/lib/common/cancel.js
> +          callback_send: cancellationCallback,
Yep

2020-11-27 06:43 UTC, DMarby commented on src/lib/common/cancel.js
> +      document.body.appendChild(s);
This is already inside the `!window.baremetrics` conditional, so it will only ever be appended once, so there's no need for additional checks or keying.

2020-11-27 08:12 UTC, develohpanda commented on src/lib/common/cancel.js
> +      document.body.appendChild(s);
Oh 🤦 my bad, you're right it is!

2020-11-27 08:14 UTC, DMarby commented on src/lib/common/cancel.js
> +      document.body.appendChild(s);
Thanks for double-checking regardless! Could potentially be really bad if this was loaded more then once 😅

2020-11-27 08:32 UTC, develohpanda approved these changes
Oops, I requested changes because of the conditional statement. Not an issue anymore!

2020-11-30 19:37 UTC, nijikokun approved these changes

2020-11-30 19:37 UTC, merged